import { useState } from "react";
import { Navbar } from "@/components/Navbar";
import { AboutDialog } from "@/components/AboutDialog";
import { Button } from "@/components/ui/button";
import { Code2, Zap, Trophy, Brain } from "lucide-react";
import { Link } from "react-router-dom";
import heroImage from "@/assets/hero-coding.jpg";

const Index = () => {
  const [aboutOpen, setAboutOpen] = useState(false);

  return (
    <div className="min-h-screen bg-gradient-hero">
      <Navbar onAboutClick={() => setAboutOpen(true)} />
      
      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-6 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-primary opacity-5" />
        
        <div className="container mx-auto relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8 animate-fade-in">
              <h1 className="text-6xl font-bold leading-tight">
                Master
                <span className="block bg-gradient-primary bg-clip-text text-transparent">
                  Python Coding
                </span>
              </h1>
              
              <p className="text-xl text-muted-foreground max-w-lg">
                Enhance your code comprehension with AI-powered quizzes. 
                Test your skills, track progress, and level up your Python expertise.
              </p>
              
              <div className="flex flex-wrap gap-4">
                <Link to="/auth">
                  <Button variant="hero" size="lg" className="text-lg px-8">
                    Start Learning
                    <Zap className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
                <Button 
                  variant="glass" 
                  size="lg" 
                  className="text-lg px-8"
                  onClick={() => setAboutOpen(true)}
                >
                  Learn More
                </Button>
              </div>
            </div>
            
            <div className="relative animate-fade-in" style={{ animationDelay: "0.2s" }}>
              <div className="relative rounded-2xl overflow-hidden shadow-glow">
                <img
                  src={heroImage}
                  alt="Coding visualization"
                  className="w-full h-auto"
                />
                <div className="absolute inset-0 bg-gradient-primary opacity-20" />
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 px-6">
        <div className="container mx-auto">
          <h2 className="text-4xl font-bold text-center mb-16 bg-gradient-primary bg-clip-text text-transparent">
            Why Choose CodeMaster?
          </h2>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-card/50 backdrop-blur-sm p-8 rounded-xl border border-primary/20 hover:border-primary/40 transition-all duration-300 animate-fade-in">
              <div className="w-14 h-14 bg-gradient-primary rounded-lg flex items-center justify-center mb-6">
                <Brain className="w-7 h-7 text-primary-foreground" />
              </div>
              <h3 className="text-2xl font-semibold mb-4">AI-Powered Quizzes</h3>
              <p className="text-muted-foreground">
                Dynamic Python questions generated by advanced AI, tailored to challenge and improve your skills.
              </p>
            </div>
            
            <div className="bg-card/50 backdrop-blur-sm p-8 rounded-xl border border-primary/20 hover:border-primary/40 transition-all duration-300 animate-fade-in" style={{ animationDelay: "0.1s" }}>
              <div className="w-14 h-14 bg-gradient-primary rounded-lg flex items-center justify-center mb-6">
                <Trophy className="w-7 h-7 text-primary-foreground" />
              </div>
              <h3 className="text-2xl font-semibold mb-4">Skill Assessment</h3>
              <p className="text-muted-foreground">
                Get categorized as Beginner, Intermediate, or Advanced based on your performance and track your growth.
              </p>
            </div>
            
            <div className="bg-card/50 backdrop-blur-sm p-8 rounded-xl border border-primary/20 hover:border-primary/40 transition-all duration-300 animate-fade-in" style={{ animationDelay: "0.2s" }}>
              <div className="w-14 h-14 bg-gradient-primary rounded-lg flex items-center justify-center mb-6">
                <Code2 className="w-7 h-7 text-primary-foreground" />
              </div>
              <h3 className="text-2xl font-semibold mb-4">Secure & Personal</h3>
              <p className="text-muted-foreground">
                Your progress is safely stored with secure authentication. Practice at your own pace, anytime.
              </p>
            </div>
          </div>
        </div>
      </section>
      
      <AboutDialog open={aboutOpen} onOpenChange={setAboutOpen} />
    </div>
  );
};

export default Index;
